version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      # Monta o diretório atual no contêiner para live-reloading
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload